### ISSUE TITLE
Visually mark Tombstones in the Frontend

### ISSUE THREAD

**Issue by weeco** [cloudhut/kafka-owl#13]
Messages with an empty value on a `compact` or `compact,delete` topic indicate a tombstone event. We should somehow mark them as Tombstone.

Either the backend or frontend could mark a message as Tombstone (this has yet to be discussed)

**Comment by rikimaru0345** [comment]
fixed in https://github.com/cloudhut/kafka-owl/commit/a32707192f2922d2bd08775d390fed5b9e7838a8
