### ISSUE TITLE
Collaborations features

### ISSUE THREAD

**Issue by rjmasikome** [cloudhut/kafka-owl#42]
These are some improvements that probably will be good for collaborations.

1. Search query for the topics (in topic list)
2. Anchor for the offset number or offset numbers (in messages tab)
3. Search query for message search (message search tab)

**Comment by rikimaru0345** [comment]
Anchor Links to a specific message are an important feature, but are actually not as straightforward  to implement as one might think.

What if I send a link to someone, but the other person opens the link a few hours later? It is possible that the last 50, 200, ... messages don't even contain the referenced message anymore.

That means when someone copies an anchor link to a specific message, that link has to contain:
- the topic name (obviously)
- the offset and partition of the message
- and the number of messages displayed

Anyway, a good idea, this should definitely be a feature.

**Comment by weeco** [comment]
> What if I send a link to someone, but the other person opens the link a few hours later? It is possible that the last 50, 200, ... messages don't even contain the referenced message anymore.

I'd say just keep it simple here. It's not given that someone sends a link in order to show the exact same messages. I'd agree with @rjmasikome  all search parameters should be part of the URL query. If someone wants to point to specific kafka message he should adapt the search accordingly and send that link afterwards.

**Comment by rikimaru0345** [comment]
1 and 3 are fixed in fdd6ef9707287aecdcf5e0306e6cec25eac8e6e5

anchor links for a specific message are coming soon

**Comment by rikimaru0345** [comment]
done
